#!/usr/bin/env node
const path = require('path')
const args = process.argv.slice(2)
const handleMigration = require('./handler')

if(!args[0]) return console.log('❌ no command given')

// wanna include some data about errors
const PATH = path.join(__dirname, '../tables/APP_DATA_TABLE.json')
const SCHEMA = JSON.stringify({
  meta: [
    {users_online: 'number'},
    {endpoints: '{route_name: {hits: number, errors: number}}'},
    {total_logins: 'number'}
  ],
  users_online: 0,
  endpoints: {
    login: {
      hits: 0,
      errors: 0,
    },
    register: {
      hits: 0,
      errors: 0,
    },
  },
  total_logins: 0,
}, null, 2)

handleMigration(args[0], {
  NAME: 'APP_DATA_TABLE',
  PATH,
  SCHEMA
})